import React from "react"
import Layout from "../components/layout"
import Head from 'next/head'

export default function Home() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <h1 className="text-red-900 text-xl">Sanity Test</h1>

        </Layout>
        
      </>
    )
  }
  